build: Add enum header to libtracker-sparql-intermediate
See https://mesonbuild.com/FAQ.html#how-do-i-tell-meson-that-my-sources-use-generated-headers

This hopefully fixes a build error that I saw:

    FAILED: src/libtracker-fts/ddda816@@tracker-fts@sta/tracker-fts.c.o
    cc -Isrc/libtracker-fts/ddda816@@tracker-fts@sta -Isrc/libtracker-fts -I../src/libtracker-fts -I. -I.. -Isrc -I../src -Isrc/libtracker-common -I../src/libtracker-common -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/gio-unix-2.0 -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wformat -Wformat-security -Wno-pointer-sign -DTRACKER_COMPILATION '-DG_LOG_DOMAIN="Tracker"' -DG_LOG_STRUCTURED=1 -O2 -g -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC -pthread -D_GNU_SOURCE -D_LARGEFILE64_SOURCE -MD -MQ 'src/libtracker-fts/ddda816@@tracker-fts@sta/tracker-fts.c.o' -MF 'src/libtracker-fts/ddda816@@tracker-fts@sta/tracker-fts.c.o.d' -o 'src/libtracker-fts/ddda816@@tracker-fts@sta/tracker-fts.c.o' -c ../src/libtracker-fts/tracker-fts.c
    In file included from ../src/libtracker-data/tracker-db-interface.h:26,
                     from ../src/libtracker-data/tracker-db-manager.h:25,
                     from ../src/libtracker-fts/tracker-fts-tokenizer.h:24,
                     from ../src/libtracker-fts/tracker-fts.c:26:
    ../src/libtracker-sparql/tracker-sparql.h:35:10: fatal error: libtracker-sparql/tracker-sparql-enum-types.h: No such file or directory
       35 | #include <libtracker-sparql/tracker-sparql-enum-types.h>
          |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Full log may be available here: https://download.copr.fedorainfracloud.org/results/ssssam/tracker3/fedora-31-x86_64/01496411-tracker3/builder-live.log.gz