build: Fix "4-digit year modifier" test
Upcoming `gcc-14` enabled a few warnings into errors, like
`-Wincompatible-pointer-types`. This caused `tracker` configure to
fail as:

    $ ../meson
    ...
    Checking if "strftime 4-digit year modifier" runs: DID NOT COMPILE

    ../meson.build:235:2: ERROR: Problem encountered: Libc implementation has broken 4-digit years implementation.

This happens because char buffer had an unusual type:

    testfile.c: In function 'main':
    testfile.c:16:17: error: passing argument 1 of 'strftime' from incompatible pointer type
    [-Wincompatible-pointer-types]
       16 |       strftime (&buf, sizeof buf, modifiers[i], &tm);
          |                 ^~~~
          |                 |
          |                 char * (*)[100]