functional-tests: Remove process watch before killing process
This sometimes causes spurious errors in 12-transactions because
the GSource gets activated somewhere between the process being
restarted, causing failures and logs like:

RuntimeError: tracker-store exited with status: -9