libtracker-sparql: Set namespace on signal argument type
This may need a hint for projects that depend on this. Otherwise
may fail like:

tracker-sparql-3.0.vapi:253.60-253.86: error: The type name `GenericArray' could not be found
  253 | 		public signal void events (string service, string graph, GenericArray<NotifierEvent> events);
      | 		                                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
Compilation failed: 1 error(s), 1 warning(s)