functional-tests: Decode query results as UTF-8 in the correct way
Previously the code would try to cast a 'str' instance to 'unicode',
which fails because it assumes the 'str' instance is valid ASCII (i.e.
all characters are in the range 0-127).

This fixes 2 test case failures that looked like this:

    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)