functional-tests: Unbreak test by removing haveMaemo conditionals
The 01-insertion.py test fails with:
  File "./01-insertion.py", line 774, in <module>
      class TrackerStorePhoneNumberTest (CommonTrackerStoreTest):
  File "./01-insertion.py", line 780, in TrackerStorePhoneNumberTest
      @ut.skipIf (not cfg.haveMaemo, "This test uses maemo:specific
        properties")
  AttributeError: 'module' object has no attribute 'haveMaemo'

The Maemo/Meego flags were removed and the 91-maemo ontology is now
installed unconditionally. Therefore there is no need to make this
test conditional.

Fallout from 809b56767fccd5680136485c6fbbc895e83dd886

https://bugzilla.gnome.org/show_bug.cgi?id=783555