tracker-extract,pdf: Use poppler-glib again for PDF extraction
The old code has been resurrected with a few changes to
have it work on Poppler 0.16.0, Now that poppler_page_get_text()
uses TextOutputDev underneath there's no need anymore to
use the C++ interface directly anymore, which is not guaranteed
to be API compatible.

Fixes Bug GB#636375 - 0.9.30: tracker-extract-pdf.cpp:
error: GlobalParams.h: No such file or directory, reported
by Andre Klapper.