ci: Remove /home/ubuntu/.bash_logout
Attempting to work around an apparent Podman issue that causes
container push failures.

See: <https://gitlab.gnome.org/GNOME/tracker/-/jobs/3950231>

    + podman push registry.gitlab.gnome.org/gnome/tracker/ubuntu/rolling:x86_64-2024-06-05.1
    Getting image source signatures
    Copying blob sha256:7e5b62f20874e0affafcc32174baf6bf45f101bf25788ed30c64e1d4693155c5
    Copying blob sha256:42d3f8788282c6e48bac7236609753b240db353465dc55cb77c21f2391720dd9
    Error: reading blob sha256:42d3f8788282c6e48bac7236609753b240db353465dc55cb77c21f2391720dd9: open /var/lib/containers/storage/vfs/dir/42d3f8788282c6e48bac7236609753b240db353465dc55cb77c21f2391720dd9/home/ubuntu/.bash_logout: permission denied
    time="2024-06-05T16:05:12Z" level=error msg="Unable to write image event: \"write unixgram @4e5be->/run/systemd/journal/socket: sendmsg: no such file or directory\""

Possible upstream issue:
<https://github.com/containers/podman/issues/8521>