docs: Check file existence merging JSON files
Even if this runs from a install script, we only merge
ontology-related JSON metadata for gi-docgen search UI once,
deleting these ancillary files after they've been merged into
the main index.json file.

This causes warnings on later `ninja install` runs if docs did
not need rebuilding, since the glob string not matching anything
is passed as-is and interpreted as a file, could be seen as:

Traceback (most recent call last):
  File ".../tracker/docs/reference/libtracker-sparql/merge-json.py", line 6, in <module>
    extra = json.load(open(sys.argv[x]))
                      ^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '../*-ontology.index.json'

Add a file existence check, to avoid this exception.