build: Fix build with meson >= 0.50
Since I got meson 0.50, tracker fails to build with:

  undefined reference to `builtin_ontology_resource_data'

when building libtracker-data.so. Do not use the compile_gresource
values individually, this seems to make meson 0.50 happy and should
work with older meson.