build: libtracker-sparql C code depends on libtracker-sparql Vala code
We need to express this dependency, otherwise the C code might fail to
build with this kind of error:

    ../src/libtracker-sparql/tracker-notifier.c:89:10: fatal error: tracker-generated-no-checks.h: No such file or directory

The `tracker-generated-no-checks.h` file is generated by Vala.

Hopefully fixes https://gitlab.gnome.org/GNOME/tracker/issues/96